/*
 * TRANSLATION FILE (ENGLIGH)
 * 
 * Alternative to stringtable.csv which is simpler to install for the mission maker.
 * The token '%1' represents a dynamic value generated by the scripts, like a vehicle name.
 * 
 * Alternative au stringtable.csv qui est plus simple à installer pour le créateur de mission.
 * Le mot-clé '%1' représente une valeur dynamique fournie par les scripts, comme par exemple un nom de véhicule.
 */

STR_R3F_LOG_action_heliporter = "貨物を吊り上げる";
STR_R3F_LOG_action_heliporter_fait = "'%1'を吊り上げた";
STR_R3F_LOG_action_heliport_larguer = "貨物を投下する";
STR_R3F_LOG_action_heliport_larguer_fait = "'%1'を投下した";
STR_R3F_LOG_action_heliport_attente = "%1を固定中...";
STR_R3F_LOG_action_heliport_echec_attente = "吊り上げ中断! 作業中は空中静止を維持してください";

STR_R3F_LOG_action_deplacer_objet = "'%1'を運ぶ;
STR_R3F_LOG_action_relacher_objet = "'%1'を置く";
STR_R3F_LOG_action_aligner_pente = "坂に向きを合わせる";
STR_R3F_LOG_action_aligner_sol = "地面に向きを合わせる";
STR_R3F_LOG_action_aligner_horizon = "水平にする";
STR_R3F_LOG_action_tourner = "左右回転 ： X / C ";
STR_R3F_LOG_action_rapprocher = "前後調整 : R / F ";
STR_R3F_LOG_ne_pas_monter_dans_vehicule = "運搬中には乗車できません";

STR_R3F_LOG_action_charger_deplace = "乗り物に積載する";
STR_R3F_LOG_action_selectionner_objet_charge = "'%1'を乗せる";
STR_R3F_LOG_action_charger_selection = "... '%1'に積載する";
STR_R3F_LOG_action_selectionner_objet_fait = "'%1'を乗せる対象を選んでください...";
STR_R3F_LOG_action_charger_en_cours = "積載中...";
STR_R3F_LOG_action_charger_fait = "'%2'に'%1'を積載しました";
STR_R3F_LOG_action_charger_pas_assez_de_place = "荷台の容量不足です";

STR_R3F_LOG_action_remorquer_direct = "'%1'を牽引する";
STR_R3F_LOG_action_remorquer_deplace = "対象に牽引させる";
STR_R3F_LOG_action_detacher = "牽引を外す";
STR_R3F_LOG_action_detacher_fait = "牽引を解除しました";
STR_R3F_LOG_action_detacher_impossible_pour_ce_vehicule = "運転手以外は牽引解除不能です";

STR_R3F_LOG_action_contenu_vehicule = "積載物を確認する";
STR_R3F_LOG_action_decharger_en_cours = "荷降ろし中...";
STR_R3F_LOG_action_decharger_fait = "'%1'を降ろしました";
STR_R3F_LOG_action_decharger_deja_fait = "この貨物は既に降りています";
STR_R3F_LOG_action_decharger_deplacable_exceptionnel = "荷物から手を離すと、手動で動かすことはできません。<br/>手を離しますか?";

STR_R3F_LOG_action_ouvrir_usine = "Open the creation factory";
STR_R3F_LOG_action_creer_en_cours = "Creation in progress...";
STR_R3F_LOG_action_creer_fait = "The object '%1' has been created.";
STR_R3F_LOG_action_creer_pas_assez_credits = "The factory has not enough credits to create this object.";
STR_R3F_LOG_action_revendre_usine_direct = "Send back '%1' to the factory";
STR_R3F_LOG_action_revendre_usine_deplace = "Send back to the factory";
STR_R3F_LOG_action_revendre_usine_selection = "... send back to the factory";
STR_R3F_LOG_action_revendre_en_cours = "Sending back to the factory...";
STR_R3F_LOG_action_revendre_fait = "The object '%1' has been sent back to the factory.";
STR_R3F_LOG_action_revendre_decharger_avant = "You can't sent it back while its cargo content is not empty !";

STR_R3F_LOG_mutex_action_en_cours = "作業中です";
STR_R3F_LOG_joueur_dans_objet = "'%1'に誰かが乗っています";
STR_R3F_LOG_objet_en_cours_transport = "'%1'は既に運搬中です";
STR_R3F_LOG_objet_remorque_en_cours = "この操作は不可能です。'%1'は他の貨物を牽引しています";
STR_R3F_LOG_trop_loin = "'%1'は遠すぎます";

STR_R3F_LOG_dlg_CV_titre = "積載中の貨物";
STR_R3F_LOG_dlg_CV_capacite_vehicule = "内容量 : %1/%2";
STR_R3F_LOG_dlg_CV_btn_decharger = "荷降ろし";
STR_R3F_LOG_dlg_CV_btn_fermer = "キャンセル";

STR_R3F_LOG_dlg_LO_titre = "Creation factory";
STR_R3F_LOG_dlg_LO_credits_restants = "Remaining credits : %1";
STR_R3F_LOG_dlg_LO_btn_creer = "CREATE";
STR_R3F_LOG_dlg_LO_btn_fermer = "CANCEL";

STR_R3F_LOG_nom_fonctionnalite_proprietes = "機能";
STR_R3F_LOG_nom_fonctionnalite_side = "Side";
STR_R3F_LOG_nom_fonctionnalite_places = "定員";
STR_R3F_LOG_nom_fonctionnalite_passif = "貨物扱い :";
STR_R3F_LOG_nom_fonctionnalite_passif_deplace = "人手で移動";
STR_R3F_LOG_nom_fonctionnalite_passif_heliporte = "被吊上";
STR_R3F_LOG_nom_fonctionnalite_passif_remorque = "被牽引";
STR_R3F_LOG_nom_fonctionnalite_passif_transporte = "被積載";
STR_R3F_LOG_nom_fonctionnalite_passif_transporte_capacite = "積載枠 %1";
STR_R3F_LOG_nom_fonctionnalite_actif = "輸送能力 :";
STR_R3F_LOG_nom_fonctionnalite_actif_heliporte = "吊上";
STR_R3F_LOG_nom_fonctionnalite_actif_remorque = "牽引";
STR_R3F_LOG_nom_fonctionnalite_actif_transporte = "貨物積載";
STR_R3F_LOG_nom_fonctionnalite_actif_transporte_capacite = "最大積載枠 %1";

STR_R3F_LOG_deverrouillage_en_cours = "%1を解錠中...";
STR_R3F_LOG_deverrouillage_echec_attente = "解錠中止しました。 一定時間対象を直視してください。";
STR_R3F_LOG_deverrouillage_succes_attente = "対象を解錠しました。";
STR_R3F_LOG_action_deverrouiller = "'%1'を解錠";
STR_R3F_LOG_action_deverrouiller_impossible = "対象は施錠されています";